# Server Configuration
server.port=9090

# Database Configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/agrisell_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Security Configuration
spring.security.user.name=admin
spring.security.user.password=admin123

# ImageKit.io auth
imagekit.publicKey=${IMAGEKIT_PUBLIC_KEY}
imagekit.privateKey=${IMAGEKIT_PRIVATE_KEY}
imagekit.urlEndpoint=${IMAGEKIT_URL_ENDPOINT}

#Stripe secret key
stripe.secret.key=${STRIPE_SECRET_KEY}

# JWT Configuration
jwt.secret=3247505e3de7ba9b1267394441fcd23558e56c428b532a8c992bcfde8be658d6
jwt.expiration=86400000

# Logging Configuration
logging.level.org.springframework=ERROR
logging.level.com.agridev=DEBUG


